/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData aboveground_rail = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airfield = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData art_gallery = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData belowground_rail = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campsite = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cemetery = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cinema = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData college = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commerical_building = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData embassy = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_food = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ferry = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_station = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fuel = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garden = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giraffe = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grocery_store = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harbor = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heliport = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData industrial_building = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_icon = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lodging = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData london_underground = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minefield = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monument = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData museum = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharmacy = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pitch = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData police = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData post = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prison = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rail = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_christian = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_islam = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_jewish = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roadblock = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theatre = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilet = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData town_hall = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_1 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_2 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
